### ISSUE TITLE
Not correct action_data when file is moved by gis-processor

### ISSUE THREAD

**Issue by ValdemarOtte** [aarhusstadsarkiv/gis-processor#13]
Der er en fejl med GIS-processor

De filer som skal flyttes over til hovedfilen får en forkert `action_data` nemlig `{"ignore": {"template": "temporary-file"}}`. Det skulle være noget i stillen med `IgnoreAction(template="text", reason=f"Moved to {new_path}")` i følge kildekoden.
Det er forkert fordi den har ignore reason som temporary-file selvom det er orginal filen

Det bemærkes også, at begge steder hvor filen er henne har `action_data: {"ignore": {"template": "temporary-file"}}`.

**Comment by MatteoCampinoti94** [comment]
Efter gis processor kører, der er to sets af auxiliary files.

## Originale filer

De originale auxiliary filer for en ignore action met template=text go reason=Moved to...

De skal ikke bevares, fordi de bliver samlet i en GML fil.

## Kopierede filer

Filerne, der er blevet kopierede til den mappe, hvor hovedfilen ligger, får en ignore action med template=temporary-file, fordi de skal 100% ignoreres.

De skal ikke bevares, fordi de bruges kun til at oprette GML filer, og de skal ikke videresendes til statutory aflevering, kun de originale filer (some templates med "moved to").

Giver det mening? :)

**Comment by MatteoCampinoti94** [comment]
Du kan se action data, som de originale filer får her:
https://github.com/aarhusstadsarkiv/gis-processor/blob/8e2adc090955bdd72942ce02eef89dbb3fe6ed15/gis_processor/cli.py#L151-L154

Og de kopiered auxiliary filer håndteres her:
https://github.com/aarhusstadsarkiv/gis-processor/blob/8e2adc090955bdd72942ce02eef89dbb3fe6ed15/gis_processor/cli.py#L175-L176

**Comment by MatteoCampinoti94** [comment]
Fixed in https://github.com/aarhusstadsarkiv/gis-processor/releases/tag/v1.0.6
