### ISSUE TITLE
New process for handling auxilary gis-files

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/gis-processor#4]
Auxilary files skal **kopieres**, inkl. metadata (pånær UUID, relative_path og action). Den kopierede fil skal have action: ignore, da convertool kun skal linkes til hovedfilen, hvorefter den automatisk behandler alle auxilary filer i samme filmappe.

Den originale auxilary-files får action = "template" og actiondata udfyldes med template-name og textcontent i templaten beskriver, at den oprindelige fil er flyttet, og bliver konverteret sammen med hovedfilen.

**Comment by MatteoCampinoti94** [comment]
![image](https://github.com/aarhusstadsarkiv/gis_processor/assets/5142004/a70e36b0-d7e5-4da7-ba8c-b8348585e9ed)
